-- Add more dog breeds for better coverage (avoiding duplicates)
INSERT INTO breeds (name, code)
SELECT name, code FROM (VALUES
-- Additional Turkish breeds
('Akbash', 'AKBASH_DOG'),
('Çatalburun', 'CATALBURUN'),
('Malaklı', 'MALAKLI'),
('Kars Çoban Köpeği', 'KARS_SHEPHERD'),
-- Popular international breeds
('Afghan Hound', 'AFGHAN_HOUND'),
('Airedale Terrier', 'AIREDALE_TERRIER'),
('Alaskan Malamute', 'ALASKAN_MALAMUTE'),
('American Bulldog', 'AMERICAN_BULLDOG'),
('American Cocker Spaniel', 'AMERICAN_COCKER'),
('American Eskimo Dog', 'AMERICAN_ESKIMO'),
('Basset Hound', 'BASSET_HOUND'),
('Belgian Shepherd', 'BELGIAN_SHEPHERD'),
('Bloodhound', 'BLOODHOUND'),
('Borzoi', 'BORZOI'),
('Bouvier des Flandres', 'BOUVIER'),
('Briard', 'BRIARD'),
('Brittany', 'BRITTANY'),
('Brussels Griffon', 'BRUSSELS_GRIFFON'),
('Cairn Terrier', 'CAIRN_TERRIER'),
('Canaan Dog', 'CANAAN_DOG'),
('Chesapeake Bay Retriever', 'CHESAPEAKE'),
('Chinese Crested', 'CHINESE_CRESTED'),
('Chinese Shar-Pei', 'SHAR_PEI'),
('Collie', 'COLLIE'),
('English Cocker Spaniel', 'ENGLISH_COCKER'),
('English Foxhound', 'ENGLISH_FOXHOUND'),
('English Pointer', 'ENGLISH_POINTER'),
('English Setter', 'ENGLISH_SETTER'),
('English Springer Spaniel', 'ENGLISH_SPRINGER'),
('Flat-Coated Retriever', 'FLAT_COATED'),
('German Pinscher', 'GERMAN_PINSCHER'),
('German Shorthaired Pointer', 'GERMAN_SHORTHAIR'),
('German Wirehaired Pointer', 'GERMAN_WIREHAIR'),
('Giant Schnauzer', 'GIANT_SCHNAUZER'),
('Gordon Setter', 'GORDON_SETTER'),
('Havanese', 'HAVANESE'),
('Ibizan Hound', 'IBIZAN_HOUND'),
('Irish Setter', 'IRISH_SETTER'),
('Irish Terrier', 'IRISH_TERRIER'),
('Irish Wolfhound', 'IRISH_WOLFHOUND'),
('Japanese Chin', 'JAPANESE_CHIN'),
('Keeshond', 'KEESHOND'),
('Kerry Blue Terrier', 'KERRY_BLUE'),
('Komondor', 'KOMONDOR'),
('Kuvasz', 'KUVASZ'),
('Labradoodle', 'LABRADOODLE'),
('Lagotto Romagnolo', 'LAGOTTO'),
('Lakeland Terrier', 'LAKELAND_TERRIER'),
('Leonberger', 'LEONBERGER'),
('Lhasa Apso', 'LHASA_APSO'),
('Manchester Terrier', 'MANCHESTER_TERRIER'),
('Mastiff', 'MASTIFF'),
('Miniature American Shepherd', 'MINI_AMERICAN'),
('Miniature Bull Terrier', 'MINI_BULL_TERRIER'),
('Miniature Pinscher', 'MINIATURE_PINSCHER'),
('Miniature Poodle', 'MINIATURE_POODLE'),
('Neapolitan Mastiff', 'NEAPOLITAN_MASTIFF'),
('Newfoundland', 'NEWFOUNDLAND'),
('Norfolk Terrier', 'NORFOLK_TERRIER'),
('Norwegian Elkhound', 'NORWEGIAN_ELKHOUND'),
('Norwich Terrier', 'NORWICH_TERRIER'),
('Nova Scotia Duck Tolling Retriever', 'NOVA_SCOTIA'),
('Old English Sheepdog', 'OLD_ENGLISH'),
('Papillon', 'PAPILLON'),
('Parson Russell Terrier', 'PARSON_RUSSELL'),
('Pekingese', 'PEKINGESE'),
('Pembroke Welsh Corgi', 'PEMBROKE_CORGI'),
('Pharaoh Hound', 'PHARAOH_HOUND'),
('Polish Lowland Sheepdog', 'POLISH_LOWLAND'),
('Portuguese Water Dog', 'PORTUGUESE_WATER'),
('Puli', 'PULI'),
('Rat Terrier', 'RAT_TERRIER'),
('Rhodesian Ridgeback', 'RHODESIAN'),
('Saluki', 'SALUKI'),
('Samoyed', 'SAMOYED'),
('Schipperke', 'SCHIPPERKE'),
('Scottish Deerhound', 'SCOTTISH_DEERHOUND'),
('Scottish Terrier', 'SCOTTISH_TERRIER'),
('Shetland Sheepdog', 'SHELTIE'),
('Shiba Inu', 'SHIBA_INU'),
('Shih Tzu', 'SHIH_TZU'),
('Silky Terrier', 'SILKY_TERRIER'),
('Smooth Fox Terrier', 'SMOOTH_FOX'),
('Soft Coated Wheaten Terrier', 'WHEATEN_TERRIER'),
('Spanish Water Dog', 'SPANISH_WATER'),
('Spinone Italiano', 'SPINONE'),
('St. Bernard', 'ST_BERNARD'),
('Standard Poodle', 'STANDARD_POODLE'),
('Standard Schnauzer', 'STANDARD_SCHNAUZER'),
('Sussex Spaniel', 'SUSSEX_SPANIEL'),
('Tibetan Mastiff', 'TIBETAN_MASTIFF'),
('Tibetan Spaniel', 'TIBETAN_SPANIEL'),
('Tibetan Terrier', 'TIBETAN_TERRIER'),
('Toy Fox Terrier', 'TOY_FOX'),
('Toy Poodle', 'TOY_POODLE'),
('Vizsla', 'VIZSLA'),
('Weimaraner', 'WEIMARANER'),
('Welsh Springer Spaniel', 'WELSH_SPRINGER'),
('Welsh Terrier', 'WELSH_TERRIER'),
('West Highland White Terrier', 'WESTIE'),
('Whippet', 'WHIPPET'),
('Wire Fox Terrier', 'WIRE_FOX'),
('Yorkshire Terrier', 'YORKSHIRE'),
('Goldendoodle', 'GOLDENDOODLE'),
('Cockapoo', 'COCKAPOO'),
('Maltipoo', 'MALTIPOO'),
('Cavapoo', 'CAVAPOO'),
('Pomsky', 'POMSKY'),
('Bernedoodle', 'BERNEDOODLE'),
('Aussiedoodle', 'AUSSIEDOODLE'),
('Schnoodle', 'SCHNOODLE'),
('Puggle', 'PUGGLE'),
('Dogo Argentino', 'DOGO_ARGENTINO'),
('Central Asian Shepherd', 'CENTRAL_ASIAN'),
('Caucasian Shepherd', 'CAUCASIAN'),
('Japanese Spitz', 'JAPANESE_SPITZ'),
('Korean Jindo', 'JINDO'),
('Belgian Tervuren', 'TERVUREN'),
('Dutch Shepherd', 'DUTCH_SHEPHERD'),
('White Swiss Shepherd', 'WHITE_SWISS'),
('Berger Picard', 'BERGER_PICARD'),
('Beauceron', 'BEAUCERON'),
('Greater Swiss Mountain Dog', 'GREATER_SWISS'),
('Perro de Presa Canario', 'PRESA_CANARIO')
) AS new_breeds(name, code)
WHERE NOT EXISTS (
  SELECT 1 FROM breeds WHERE breeds.name = new_breeds.name OR breeds.code = new_breeds.code
);